services:
  ratelimiter:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
      - postgres
    environment:
      - PORT=8000
    networks:
      - ratelimiter

  redis:
    restart: always
    container_name: redis
    image: redis:6.2.11-alpine3.17
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

    networks:
      - ratelimiter

  postgres:
    restart: always
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    

networks:
  ratelimiter:
    driver: bridge